version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2017
clone_depth: 1
clone_folder: c:\cc\analyzer
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_file_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_informational_version: $(APPVEYOR_REPO_TAG_NAME)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
environment:
  COVERALLS_REPO_TOKEN:
    secure: sy1uboCBXj09+y+KDXe0Ws9ru+eqenydlidc1CwlqcJnbLn72cYG476yh0AjU8jp
  SONARQUBE_TOKEN:
    secure: Oh/eULUJNuQcby4Rp0+gvp9gA5SbxkCeuK8L7qZGUvguXpO6YYpFmEHjXI2PCe/b
  SONARQUBE:
    secure: Oh/eULUJNuQcby4Rp0+gvp9gA5SbxkCeuK8L7qZGUvguXpO6YYpFmEHjXI2PCe/b
  CONFIGURATION: Release
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build\build_script.ps1
test_script:
- ps: .\build\test_script.ps1
artifacts:
- path: '**\*.nupkg'
  name: NuGet-Release
deploy:
- provider: Environment
  name: NuGet-Release
- provider: Environment
  name: GitHub-Release